name: topkapi_bank
description: This app created for banking system

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <=3.0.1'


dependencies:
  flutter:
    sdk: flutter

  #Localizations
  ntp: ^2.0.0
  intl: ^0.17.0

  #credit card ui
  u_credit_card: ^1.0.3

  #slide dialog
  slide_popup_dialog_null_safety: ^1.0.0


  #charts
  circular_chart_flutter: ^0.0.2

  #slider
  flutter_carousel_slider: ^1.1.0

  #cached_network_image:
  cached_network_image: ^3.2.3

  #tabbar:
  tab_container: ^2.0.0
  flutter_advanced_drawer: ^1.3.5

  #qr_flutter:
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1

  #date
  date_time_picker: ^2.1.0

  #path
  path_provider: ^2.0.15
  android_path_provider: ^0.3.0

  #state managment
  flutter_riverpod: ^2.3.6
  state_notifier: ^0.7.2+1

  #Model Works
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  freezed_annotation: ^2.2.0


  #ui_helpers
  responsive_sizer: ^3.1.1
  search_choices: ^2.2.1
  anim_search_bar: ^2.0.3
  awesome_dialog: ^3.0.2

  #version_control
  package_info_plus: ^4.0.0

  #Firebase Database
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  cloud_firestore: ^4.7.1

  #appBadger
  flutter_app_badger: ^1.5.0

  #Push Notification
  flutter_local_notifications: ^14.0.0+2
  firebase_messaging: ^14.6.1



  #local_db
  hive: ^2.2.3

  #uniqueid
  nanoid: ^1.0.0
  #httprequest
  dio: ^4.0.6

  #log control
  logger: ^1.3.0

  equatable: ^2.0.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4


flutter:

  uses-material-design: true

  assets:

    - assets/image/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf
